#!/bin/bash

BLACK=`echo "\033[30m"`
RED=`echo "\033[31m"`
GREEN=`echo "\033[32m"`
BROWN=`echo "\033[33m"`
BLUE=`echo "\033[34m"`
PURPLE=`echo "\033[35m"`
CYAN=`echo "\033[36m"`
LGRAY=`echo "\033[37m"`
DGRAY=`echo "\033[1;30m"`
LRED=`echo "\033[1;31m"`
LGREEN=`echo "\033[1;32m"`
YELLOW=`echo "\033[1;33m"`
LBLUE=`echo "\033[1;34m"`
LPURPLE=`echo "\033[1;35m"`
LCYAN=`echo "\033[1;36m"`
WHITE=`echo "\033[1;37m"`
NORMAL=`echo "\033[m"`

# FOR SETTING PS1
PS_CYAN="\e[0;36m";
PS_UCYAN="\e[4;36m";
PS_LCYAN="\e[1;36m";
PS_LPURPLE="\e[1;35m";
PS_GREEN="\e[0;32m";
PS_RED="\e[0;31m";
PS_NORMAL="\e[0m";
