#!/bin/bash

alias cdd='cd ~/Desktop';
alias cddow='cd ~/Downloads';
alias ..='cd ..';
alias ...='cd ../..';
alias .4='cd ../../..';
alias .5='cd ../../../..';
alias .b='cd -';

### ls ###
alias ls='ls --color=auto';
alias l.='ls -d .*';
alias la='ls -lA';
alias l1='ls -1F';
alias ll='ls -AlF'
alias l='ls -CF'

alias pwla='echo;pwd;la;echo';

#grep
function grh-func() { ls -CF1 ./${1} | grep html; }
alias grh="grh-func"
function grc-func() { ls -CF1 ./${1} | grep css; }
alias grc="grc-func"

alias lag='ls -la | grep';

# pushd/popd
function p-func() { pushd ${1} > /dev/null; echo -e "${GREEN}`dirs -v`${NORMAL}"; }
alias p="p-func"
function o-func() { popd ${1} > /dev/null; echo -e "${GREEN}`dirs -v`${NORMAL}"; }
alias o="o-func"
alias d="echo -e \"${GREEN}`dirs -v`${NORMAL}\""


alias c='clear';

alias mkdir='mkdir -pv';

alias sbb='"$BASH" -cl "sudo $(history -p !!)"';

# runs a command ${1} with the previous command's arguments
function abb-func() { $BASH -cl "${1} $(history -p !!:*)"; }
alias abb='abb-func';

### pwd ###
function pwd-color-func() {
  cd ..;
  echo -ne "${GREEN}`\pwd`/${NORMAL}";
  cd - > /dev/null;
  echo -e "${LBLUE}`\pwd | awk -F "/" '{print $NF}'`${NORMAL}";
}
alias pwd="pwd-color-func";

# TODO : needs work to make it work from any partial path
function path() {
	full=`readlink -e ${1}`;
	if [ $? -eq 0 ]; then
		path=`echo $full | grep -o '.*/'`;
  	echo -ne "${GREEN}${path}${NORMAL}";
  	echo -e "${LBLUE}${1}${NORMAL}";
  	return 0
  else
  	echo -e "${RED}File does not exist${NORMAL}"
  	return 1
  fi
}



##################################

