#!/bin/bash


### shell ###
[ "$TERM" = dumb ] && export TERM=xterm




# alias viba='vim /home/zamalchi/.bash_config';
# alias eba='emacs -nw /home/zamalchi/.bash_config';

# if [ -f /etc/lsb-release ]; then
#     . /etc/lsb-release
#     OS=$DISTRIB_ID
#     VER=$DISTRIB_RELEASE

# elif [ -f /etc/debian_version ]; then
#     OS=Debian
#     VER=$(cat /etc/debian_version)

# elif [ -f /etc/redhat-release ]; then
#     OS=RedHat

# else
#     OS=$(uname -s)
#     VER=$(uname -r)

# fi

############################################

PARENT_DIR=$( cd "$(dirname "${BASH_SOURCE}")" ; \pwd -P )


# source all the files in bash-config/partials/
if [ -d ${PARENT_DIR}/partials ]; then
	for f in ${PARENT_DIR}/partials/*; do
			# alias path
			# if [ $? -eq 0 ]; then
  			# echo "sourcing : `path ${f}`"
  		# else
			echo "sourcing : ${f}"
  		# fi
  		. "$f";
	done
fi

PATH=$PATH:$HOME/bin

export PATH